fix: solcuionado build elimiunando costtech

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,5 +28,8 @@ jobs:
             pnpm install
             pnpm prisma generate
             pnpm migrate
-            pnpm build
+            if ! pnpm build; then
+              echo "Build failed"
+              exit 1
+            fi
             pm2 restart listado-st || pm2 start "pnpm start" --name listado-st
